export default class FileTyype {
    public static Types = {
        'code:bat': 'ace/mode/batchfile',
        'code:c': 'ace/mode/c_cpp',
        'code:cpp': 'ace/mode/c_cpp',
        'code:csharp': 'ace/mode/csharp',
        'code:css': 'ace/mode/css',
        'code:clojure': 'ace/mode/clojure',
        'code:coffeescript': 'ace/mode/coffee',
        'code:dockerfile': 'ace/mode/dockerfile',
        'code:go': 'ace/mode/golang',
        'code:groovy': 'ace/mode/groovy',
        'code:html': 'ace/mode/html',
        'code:handlebars': 'ace/mode/handlebars',
        'code:ini': 'ace/mode/ini',
        'code:java': 'ace/mode/java',
        'code:javascript': 'ace/mode/javascript',
        'code:javascriptreact': 'ace/mode/javascript',
        'code:json': 'ace/mode/json',
        'code:jade': 'ace/mode/jade',
        'code:less': 'ace/mode/less',
        'code:lua': 'ace/mode/lua',
        'code:makefile': 'ace/mode/makefile',
        'code:markdown': 'ace/mode/markdown',
        'code:objective-c': 'ace/mode/objectivec',
        'code:perl': 'ace/mode/perl',
        'code:perl6': 'ace/mode/perl',
        'code:php': 'ace/mode/php',
        'code:plaintext': 'ace/mode/plain_text',
        'code:python': 'ace/mode/python',
        'code:powershell': 'ace/mode/powershell',
        'code:r': 'ace/mode/r',
        'code:ruby': 'ace/mode/ruby',
        'code:rust': 'ace/mode/rust',
        'code:sql': 'ace/mode/sql',
        'code:sass': 'ace/mode/sass',
        'code:shellscript': 'ace/mode/sh',
        'code:swift': 'ace/mode/swift',
        'code:typescript': 'ace/mode/typescript',
        'code:typescriptreact': 'ace/mode/typescript',
        'code:vb': 'ace/mode/vbscript',
        'code:xml': 'ace/mode/xml',
        'code:yaml': 'ace/mode/yaml'
    }
}
